# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/temur/Documents/Astro/latest_code_2024_09_21/ray_based_ziji/github_version/git/black_ziji

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/temur/Documents/Astro/latest_code_2024_09_21/ray_based_ziji/github_version/git/black_ziji

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/temur/Documents/Astro/latest_code_2024_09_21/ray_based_ziji/github_version/git/black_ziji/CMakeFiles /Users/temur/Documents/Astro/latest_code_2024_09_21/ray_based_ziji/github_version/git/black_ziji//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/temur/Documents/Astro/latest_code_2024_09_21/ray_based_ziji/github_version/git/black_ziji/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named transit_ray

# Build rule for target.
transit_ray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 transit_ray
.PHONY : transit_ray

# fast build rule for target.
transit_ray/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/build
.PHONY : transit_ray/fast

#=============================================================================
# Target rules for targets named lpg

# Build rule for target.
lpg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lpg
.PHONY : lpg

# fast build rule for target.
lpg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/build
.PHONY : lpg/fast

#=============================================================================
# Target rules for targets named line_bin

# Build rule for target.
line_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 line_bin
.PHONY : line_bin

# fast build rule for target.
line_bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/line_bin.dir/build.make CMakeFiles/line_bin.dir/build
.PHONY : line_bin/fast

#=============================================================================
# Target rules for targets named reb_bin

# Build rule for target.
reb_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reb_bin
.PHONY : reb_bin

# fast build rule for target.
reb_bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reb_bin.dir/build.make CMakeFiles/reb_bin.dir/build
.PHONY : reb_bin/fast

#=============================================================================
# Target rules for targets named all_targets

# Build rule for target.
all_targets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_targets
.PHONY : all_targets

# fast build rule for target.
all_targets/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_targets.dir/build.make CMakeFiles/all_targets.dir/build
.PHONY : all_targets/fast

#=============================================================================
# Target rules for targets named clean_cache

# Build rule for target.
clean_cache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_cache
.PHONY : clean_cache

# fast build rule for target.
clean_cache/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean_cache.dir/build.make CMakeFiles/clean_cache.dir/build
.PHONY : clean_cache/fast

zijiray/src/GR/geodesic.o: zijiray/src/GR/geodesic.cc.o
.PHONY : zijiray/src/GR/geodesic.o

# target to build an object file
zijiray/src/GR/geodesic.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/GR/geodesic.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/GR/geodesic.cc.o
.PHONY : zijiray/src/GR/geodesic.cc.o

zijiray/src/GR/geodesic.i: zijiray/src/GR/geodesic.cc.i
.PHONY : zijiray/src/GR/geodesic.i

# target to preprocess a source file
zijiray/src/GR/geodesic.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/GR/geodesic.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/GR/geodesic.cc.i
.PHONY : zijiray/src/GR/geodesic.cc.i

zijiray/src/GR/geodesic.s: zijiray/src/GR/geodesic.cc.s
.PHONY : zijiray/src/GR/geodesic.s

# target to generate assembly for a file
zijiray/src/GR/geodesic.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/GR/geodesic.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/GR/geodesic.cc.s
.PHONY : zijiray/src/GR/geodesic.cc.s

zijiray/src/GR/metric.o: zijiray/src/GR/metric.cc.o
.PHONY : zijiray/src/GR/metric.o

# target to build an object file
zijiray/src/GR/metric.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/GR/metric.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/GR/metric.cc.o
.PHONY : zijiray/src/GR/metric.cc.o

zijiray/src/GR/metric.i: zijiray/src/GR/metric.cc.i
.PHONY : zijiray/src/GR/metric.i

# target to preprocess a source file
zijiray/src/GR/metric.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/GR/metric.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/GR/metric.cc.i
.PHONY : zijiray/src/GR/metric.cc.i

zijiray/src/GR/metric.s: zijiray/src/GR/metric.cc.s
.PHONY : zijiray/src/GR/metric.s

# target to generate assembly for a file
zijiray/src/GR/metric.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/GR/metric.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/GR/metric.cc.s
.PHONY : zijiray/src/GR/metric.cc.s

zijiray/src/lpg/main.o: zijiray/src/lpg/main.cc.o
.PHONY : zijiray/src/lpg/main.o

# target to build an object file
zijiray/src/lpg/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/lpg/main.cc.o
.PHONY : zijiray/src/lpg/main.cc.o

zijiray/src/lpg/main.i: zijiray/src/lpg/main.cc.i
.PHONY : zijiray/src/lpg/main.i

# target to preprocess a source file
zijiray/src/lpg/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/lpg/main.cc.i
.PHONY : zijiray/src/lpg/main.cc.i

zijiray/src/lpg/main.s: zijiray/src/lpg/main.cc.s
.PHONY : zijiray/src/lpg/main.s

# target to generate assembly for a file
zijiray/src/lpg/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/lpg/main.cc.s
.PHONY : zijiray/src/lpg/main.cc.s

zijiray/src/raytrace/raygen.o: zijiray/src/raytrace/raygen.cc.o
.PHONY : zijiray/src/raytrace/raygen.o

# target to build an object file
zijiray/src/raytrace/raygen.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/raytrace/raygen.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/raytrace/raygen.cc.o
.PHONY : zijiray/src/raytrace/raygen.cc.o

zijiray/src/raytrace/raygen.i: zijiray/src/raytrace/raygen.cc.i
.PHONY : zijiray/src/raytrace/raygen.i

# target to preprocess a source file
zijiray/src/raytrace/raygen.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/raytrace/raygen.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/raytrace/raygen.cc.i
.PHONY : zijiray/src/raytrace/raygen.cc.i

zijiray/src/raytrace/raygen.s: zijiray/src/raytrace/raygen.cc.s
.PHONY : zijiray/src/raytrace/raygen.s

# target to generate assembly for a file
zijiray/src/raytrace/raygen.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/raytrace/raygen.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/raytrace/raygen.cc.s
.PHONY : zijiray/src/raytrace/raygen.cc.s

zijiray/src/raytrace/raypath.o: zijiray/src/raytrace/raypath.cc.o
.PHONY : zijiray/src/raytrace/raypath.o

# target to build an object file
zijiray/src/raytrace/raypath.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/raytrace/raypath.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/raytrace/raypath.cc.o
.PHONY : zijiray/src/raytrace/raypath.cc.o

zijiray/src/raytrace/raypath.i: zijiray/src/raytrace/raypath.cc.i
.PHONY : zijiray/src/raytrace/raypath.i

# target to preprocess a source file
zijiray/src/raytrace/raypath.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/raytrace/raypath.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/raytrace/raypath.cc.i
.PHONY : zijiray/src/raytrace/raypath.cc.i

zijiray/src/raytrace/raypath.s: zijiray/src/raytrace/raypath.cc.s
.PHONY : zijiray/src/raytrace/raypath.s

# target to generate assembly for a file
zijiray/src/raytrace/raypath.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/raytrace/raypath.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/raytrace/raypath.cc.s
.PHONY : zijiray/src/raytrace/raypath.cc.s

zijiray/src/transit/main.o: zijiray/src/transit/main.cc.o
.PHONY : zijiray/src/transit/main.o

# target to build an object file
zijiray/src/transit/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/transit/main.cc.o
.PHONY : zijiray/src/transit/main.cc.o

zijiray/src/transit/main.i: zijiray/src/transit/main.cc.i
.PHONY : zijiray/src/transit/main.i

# target to preprocess a source file
zijiray/src/transit/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/transit/main.cc.i
.PHONY : zijiray/src/transit/main.cc.i

zijiray/src/transit/main.s: zijiray/src/transit/main.cc.s
.PHONY : zijiray/src/transit/main.s

# target to generate assembly for a file
zijiray/src/transit/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/transit/main.cc.s
.PHONY : zijiray/src/transit/main.cc.s

zijiray/src/utils/physics.o: zijiray/src/utils/physics.cc.o
.PHONY : zijiray/src/utils/physics.o

# target to build an object file
zijiray/src/utils/physics.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/utils/physics.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/utils/physics.cc.o
.PHONY : zijiray/src/utils/physics.cc.o

zijiray/src/utils/physics.i: zijiray/src/utils/physics.cc.i
.PHONY : zijiray/src/utils/physics.i

# target to preprocess a source file
zijiray/src/utils/physics.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/utils/physics.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/utils/physics.cc.i
.PHONY : zijiray/src/utils/physics.cc.i

zijiray/src/utils/physics.s: zijiray/src/utils/physics.cc.s
.PHONY : zijiray/src/utils/physics.s

# target to generate assembly for a file
zijiray/src/utils/physics.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transit_ray.dir/build.make CMakeFiles/transit_ray.dir/zijiray/src/utils/physics.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lpg.dir/build.make CMakeFiles/lpg.dir/zijiray/src/utils/physics.cc.s
.PHONY : zijiray/src/utils/physics.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... all_targets"
	@echo "... clean_cache"
	@echo "... line_bin"
	@echo "... reb_bin"
	@echo "... lpg"
	@echo "... transit_ray"
	@echo "... zijiray/src/GR/geodesic.o"
	@echo "... zijiray/src/GR/geodesic.i"
	@echo "... zijiray/src/GR/geodesic.s"
	@echo "... zijiray/src/GR/metric.o"
	@echo "... zijiray/src/GR/metric.i"
	@echo "... zijiray/src/GR/metric.s"
	@echo "... zijiray/src/lpg/main.o"
	@echo "... zijiray/src/lpg/main.i"
	@echo "... zijiray/src/lpg/main.s"
	@echo "... zijiray/src/raytrace/raygen.o"
	@echo "... zijiray/src/raytrace/raygen.i"
	@echo "... zijiray/src/raytrace/raygen.s"
	@echo "... zijiray/src/raytrace/raypath.o"
	@echo "... zijiray/src/raytrace/raypath.i"
	@echo "... zijiray/src/raytrace/raypath.s"
	@echo "... zijiray/src/transit/main.o"
	@echo "... zijiray/src/transit/main.i"
	@echo "... zijiray/src/transit/main.s"
	@echo "... zijiray/src/utils/physics.o"
	@echo "... zijiray/src/utils/physics.i"
	@echo "... zijiray/src/utils/physics.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

